apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-3kbr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-3kbr
    app.kubernetes.io/part-of: tkrw-pr712-0075-0068-app
  name: devfile-sample-3kbr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-3kbr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-3kbr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-3kbr@sha256:c6ec53dbd5163c90fa06516f669969baf8a242c3e72afb04f3c94c400052eb5c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
