apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3kbr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-3kbr@sha256:c6ec53dbd5163c90fa06516f669969baf8a242c3e72afb04f3c94c400052eb5c
        name: my-nodejs
        resources: {}
status: {}
